vtdec: Use kVTVideoDecoderReferenceMissingErr only when defined
The enum value is declared present since macOS 10.8+[1]. Howerver,
the compilation now fails with the 10.15 SDK:
```
../sys/applemedia/vtdec.c:1219:12: error: use of undeclared identifier 'kVTVideoDecoderReferenceMissingErr'; did you mean 'kVTVideoDecoderMalfunctionErr'?
      case kVTVideoDecoderReferenceMissingErr:
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           kVTVideoDecoderMalfunctionErr
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/VideoToolbox.framework/Headers/VTErrors.h:40:2: note: 'kVTVideoDecoderMalfunctionErr' declared here
        kVTVideoDecoderMalfunctionErr                   = -12911, // c.f. -8960
        ^
1 error generated.
```

Put the enum usage under #ifdef. When missing, the behavior will be
the same as before commit a5c437c6430cdce603e46e09400beb4c5b9f5374.

[1] https://developer.apple.com/documentation/videotoolbox/kvtvideodecoderreferencemissingerr?language=objc